import { Warehouse } from "@/sections/warehouse/types/Warehouse";

export const mockWarehouses: Warehouse[] = [
  {
    id: "wh-1",
    name: "Almacén Central",
    address: "Av. Industrial 123, Madrid",
    capacity: 10000,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "wh-2",
    name: "Almacén Norte",
    address: "Calle Logística 456, Barcelona",
    capacity: 5000,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "wh-3",
    name: "Almacén Sur",
    address: "Polígono Industrial, Sevilla",
    capacity: 7500,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "wh-4",
    name: "Almacén Este",
    address: "Zona Franca, Valencia",
    capacity: 6000,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "wh-5",
    name: "Almacén Oeste",
    address: "Puerto Comercial, Bilbao",
    capacity: 8500,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "wh-6",
    name: "Almacén Regional Zaragoza",
    address: "Plaza Logística, Zaragoza",
    capacity: 4500,
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "wh-7",
    name: "Almacén Málaga",
    address: "Centro Distribución, Málaga",
    capacity: 5500,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "wh-8",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-9",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-10",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-11",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-12",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-13",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-14",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "wh-15",
    name: "Almacén Murcia",
    address: "Parque Industrial, Murcia",
    capacity: 3500,
    createdAt: new Date("2024-04-10"),
  },
];

// export const mockLocations: Location[] = [
//   { id: 'loc-1', warehouseId: 'wh-1', zone: 'A', aisle: '1', rack: '1', level: '1', position: 'A', capacity: 100 },
//   { id: 'loc-2', warehouseId: 'wh-1', zone: 'A', aisle: '1', rack: '1', level: '2', position: 'A', capacity: 100 },
//   { id: 'loc-3', warehouseId: 'wh-1', zone: 'B', aisle: '2', rack: '1', level: '1', position: 'B', capacity: 150 },
//   { id: 'loc-4', warehouseId: 'wh-2', zone: 'A', aisle: '1', rack: '1', level: '1', position: 'A', capacity: 80 },
// ]
/*
export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'LAP-001',
    name: 'Laptop Dell XPS 15',
    description: 'Laptop profesional con procesador Intel i7',
    category: 'Electrónica',
    imageUrl: '/modern-laptop-workspace.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'prod-2',
    sku: 'MON-002',
    name: 'Monitor LG 27"',
    description: 'Monitor 4K para diseño gráfico',
    category: 'Electrónica',
    imageUrl: '/computer-monitor.png',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'prod-3',
    sku: 'KEY-003',
    name: 'Teclado Mecánico',
    description: 'Teclado gaming RGB',
    category: 'Accesorios',
    imageUrl: '/mechanical-keyboard.png',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'prod-4',
    sku: 'MOU-004',
    name: 'Mouse Inalámbrico',
    description: 'Mouse ergonómico para oficina',
    category: 'Accesorios',
    imageUrl: '/field-mouse.png',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
]
*/

/*
export const mockInventory: Inventory[] = [
  {
    id: 'inv-1',
    productId: 'prod-1',
    warehouseId: 'wh-1',
    locationId: 'loc-1',
    quantity: 45,
    minStock: 10,
    maxStock: 100,
    lastUpdated: new Date('2024-03-15'),
  },
  {
    id: 'inv-2',
    productId: 'prod-2',
    warehouseId: 'wh-1',
    locationId: 'loc-2',
    quantity: 5,
    minStock: 15,
    maxStock: 50,
    lastUpdated: new Date('2024-03-14'),
  },
  {
    id: 'inv-3',
    productId: 'prod-3',
    warehouseId: 'wh-1',
    locationId: 'loc-3',
    quantity: 120,
    minStock: 20,
    maxStock: 200,
    lastUpdated: new Date('2024-03-16'),
  },
  {
    id: 'inv-4',
    productId: 'prod-4',
    warehouseId: 'wh-2',
    locationId: 'loc-4',
    quantity: 0,
    minStock: 10,
    maxStock: 100,
    lastUpdated: new Date('2024-03-10'),
  },
]
*/

/*
export const mockMovements: Movement[] = [
  {
    id: 'mov-1',
    type: 'entrada',
    productId: 'prod-1',
    warehouseId: 'wh-1',
    locationId: 'loc-1',
    quantity: 50,
    reason: 'Pedido proveedor #1234',
    performedBy: 'Juan Pérez',
    createdAt: new Date('2024-03-15T10:30:00'),
  },
  {
    id: 'mov-2',
    type: 'salida',
    productId: 'prod-1',
    warehouseId: 'wh-1',
    locationId: 'loc-1',
    quantity: 5,
    reason: 'Venta #5678',
    performedBy: 'María García',
    createdAt: new Date('2024-03-15T14:20:00'),
  },
  {
    id: 'mov-3',
    type: 'entrada',
    productId: 'prod-3',
    warehouseId: 'wh-1',
    locationId: 'loc-3',
    quantity: 100,
    reason: 'Pedido proveedor #1235',
    performedBy: 'Juan Pérez',
    createdAt: new Date('2024-03-16T09:00:00'),
  },
  {
    id: 'mov-4',
    type: 'ajuste',
    productId: 'prod-2',
    warehouseId: 'wh-1',
    locationId: 'loc-2',
    quantity: -10,
    reason: 'Corrección inventario',
    performedBy: 'Ana López',
    createdAt: new Date('2024-03-14T16:45:00'),
  },
]*/
